language: scala
sudo: false
scala:

- 2.12.3

jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/
  - $HOME/.sbt/cache/
  - $HOME/.sbt/boot/
  - $HOME/.sbt/launchers/
env:
  matrix:
    secure: PQgIsR7yv3p9OJq8VJz41MDCmoIaE5Y1XQQER+pXnkuov2gUNZL3MUUFrtgLnNKNEMTqtv8E+EAyhITE8nACeThsws8FFrSla7GO/T6YBVcvJChJc/pQjUO928J9KrE3cyKGV5tR8gQR+/HPy9amBtloCGLhJ7NG0dG/4Lsh7V6kYhabvC1mqO+KZEOVvEYTfXZzZaHKkKYxTJ6+gSTOAFJdpwAOdZDzbgZQWr+Si6B86YZdvvqHSTQoaNM4WntaYvPnmMhqxBtltL1cyRC8eP+/yckeRtjmSefPeyYEMJl0S/kwhaVJmj5vxP+dYGDCi35YVO6nONUzgphc149jTzFmVKPOdM9fgOmjkV5DnCDIicbJlyTKzsa8I0BvEVXqaPc080O8x9innfhGHaEx2oxpxz3mYluC8kSGotfLzkspzJsJLsxshhUJF9WVvkHfHmCn2El+mOBwh6Gw1tAHPBHU9Yrn6iuRtvjdgBIaP02LIg/SvqiGe7NLhI55AkwclTs1T148ghVANaHWWEbs+GwPGHwt11KHZqBvbxfWbhCF8hjVSccDC0K9ipnw3eUJtbUe5xXtU2XJJ7VmimCA/76fTWWz0QRlXrDvn7eelR0qgRl9BHLIcFlGNaZBJSvgfqKBQLXSJwOK7PEqnKAPO/k2H7S4vGDP2PEPQQMgR2w=
script:
  - sbt test
  - sbt clean coverage test 
  - sbt coverageReport coverageAggregate codacyCoverage
