language: scala
sudo: false
scala:
- 2.12.4
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/"
  - "$HOME/.sbt/cache/"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
script:
- sbt test
- sbt clean coverage test
- sbt coverageReport coverageAggregate codacyCoverage
env:
  matrix:
    secure: zfVwPKnE82W/DKlAqAM80eHrk/K8IlUKR68KKEx1NSOaoHRJZkKVkSWKzmu7eV/btbQWEKBegzV85+LiNGFq9AaoBJLD0ix3r8ISMHcCLGpNeTpT9AKrVIfwbttk7tpw+HKc1ySDy7hPl5ZeBOjh2jjynGZJklnPczU/XlFk0FGgXvY/iVdeIY0xYOD60i9xXgnuf9oCr/5SHdGhmFN3LOV/Ah/tBVi70uC8PUOoEBNSvRYNMyE6fDSv3V0BccHlRUspjnk0ZplTNYRH5xwgGejXOQwNboJXShDQYX397S8md5WeWf8ukTnd/0ICtOjKTzL5srNO/gw87Y1yZx1rNO+o0Y8HADcBNNwngMHCgKXsA57FGO4grE23+wZJdz8BqwVJsqXcX/lGSWf10XWprIGKKQTPrfBR2QmFtX7dAyPsGJIqzDmwJrAWjx14/vLKGTC4IozChWr0+Rrg1q0/K0Gzxc32ZY16doKSw92K53UZZhG0yRMpuZZS3sSVlusZdqkH1VSoCECbS0W3IDV+NAWXUgY9wVKZSo8wK0Tpyjawm45tM3DC8ez7Cj47eKZ7SecE3SEJ/kojMy04heX9uVs7TTVMcemGsF17dine0q1c5n9pJXYvLFURmwWhnpHwUt7vOsauPpLe/lWfqhghdOsRLNq49qiycule9Y9sp/E=
