language: scala
sudo: false
scala:
- 2.12.4
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/"
  - "$HOME/.sbt/cache/"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
script:
- sbt test
- sbt clean coverage test
- sbt coverageReport coverageAggregate codacyCoverage
env:
  matrix:
    secure: T4ommPAX3vD8wU+4duFPrlrHd5WH9sIJemuvusi+nyWmQOkx0x4ybv5iG7opl0NaDvucmjDq/tlfqJwZ0pE6sn41joH4Us4PU5GgvzRmsWsOBKWQ8+h/jJjfh5TMlIQe8CfjzEYNAHzAND27xLgzLAIj8TXE2sBMsptUSzdDU6H8tOpqTMqZKD2mgb3HuqPsgSxE5wWky5eHsmS962oOLNmg0k8yRz4OksOz/+z1pXaTyPB9nc/G6eqpFs5iqJ4IiUOp48P3Y0T4aj82ZuHOeh8bZ9L7uoXxH5Ri/4PYJ6h7b/PgyxO32YLXzLStL3YYuRSKyMH6i3Y/1iKxyOEqpP7Hqcvlm05qyirphUngZ3dRQgxMESI/SvNPnaGRORSot0EWkUyh1o1GAtq7C6DYDscMSGwAHBy8SQK5E5VeWhTejUGq7KxDaqp89htk8xIFrGWpLuGPmLvYaAtNERvKT5PRazgQWFHlMxyAO+854lYJbVHTKNl+K2GFjR5tqAwEGvOswCmbNmxKEytN9GG3lZ2XCGIEyjAM2aWEIqlLGRD40SJ8PPD5GhCt93WGquB1HQk0wBIX6TYCektGg1w5Njb/Pa/7PXapxdyBYaFDPjCArFtBaxeQ6CJplyCzDVRPfe+scqG4u+F54ODiKXHJU6OsmNi0BjsFQOcBNO39Pyo=
