language: scala
sudo: false
scala:
- 2.12.4
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/"
  - "$HOME/.sbt/cache/"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
script:
- sbt test
- sbt clean coverage test
- sbt coverageReport coverageAggregate codacyCoverage
env:
  matrix:
    secure: fbeWsFsmWrxYdsl6ktR8qxagOVYItnmtaV8V/8TpHPXgG0buu9Nd/1z46fnMkBCj9jInZp6z8tYp1mR9/empBOsgveR9kfzCRXNe9fqZHCPad2uiB860bY1cmV19ViUtBz9mMsiNh6DzDdN9pmCGAN4zGUjC2CA8/US2Pr1Hm1kZR2iT+Nm0WtFI1wX3NCZFw4t0U8XENoByq26zrHDHkT1jJZfjC/IMSZiPdRuGuUagoKfIEGwrOEO96PuElYuOQG3P39ezwnJaVokU5Pkt1QJRb/ZL7X/WWzFOhghoxjiwpeencDJoGkDxNjF8LINz5OXGYerZQ0sq14JSSsZQXa91ilDIZ7qZar9SQ89S6W6M/fvGhpajNufn8KXsesMRLIoZIfQudFsldepXBowmlFrtOd19NnSyGose4ST6ESB52Guly9yNMhtxIfcgULWp0+rpCgBa+S46w6dMNBFlKaOLbDBt7xXWqsu/Wc58OLhR4n9IyD9fuVVhfVczMebYkyrEndLQvH25BR461sJdH24jWyPYzJPVuPUnTqI5WSFjiAoubQ1AUwPbwYhCcQ5MndmH6dkh2gNdp59o6IfSjB9Dm6GtRUSA+vfbODKYaK8Pqas2GKnyWztQnSd0dy6zj91ek9xMGL2xu3FFvhIelHhb2f0zr5Jy0Wxd25QNllg=
